version: '3.4'
services:
  fastapi:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - ./config/.env.prod
    working_dir: /app